title: <p> Ameet Kumar </p>
logo: /assets/img/Ameet.jpg

description:
  <p align="center">
  <a href="https://github.com/srvameet">GitHub</a>
  
  <br>   
  I'm learning AI & ML.
  <br>
  </p>



theme: jekyll-theme-minimal
